### ISSUE TITLE
전체 프로젝트 도커 실행 환경 구성

### ISSUE THREAD

**Issue by JadenKim-dev** [Nimble-Meet/server#1]
## Task Summary

- 전체 프로젝트를 docker를 이용하여 실행 가능하도록 구성

## Description

- [ ]  백엔드 + 프론트 각각 dockerize
- [ ]  nginx를 통한 프록시
- [ ]  docker compose를 이용한 전체 도커 컨테이너 실행
